language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: albenoit-github
# command to run tests
script:
  - pytest -v --cov .
  - test_S2.py
  #- sonar-scanner
  #- coveralls
